### ISSUE TITLE
[BUG]: Failed to compile template '/Users/<user>/Projects/test-theme/vsf-core/modules/magento/plugin.ts'. Setup new project: When I try to use vsf-tu command with a new VSF Magento project on version 1.0.0-rc.10  an error appears.

### ISSUE THREAD

**Issue by bold-dkdewijer** [vuestorefront/theme-utilities#18]
When I setup a new store for Magento 2 (with VSF Magento version: 1.0.0-rc.10 ) using VSF by entering the following commands: 

npx @vue-storefront/cli generate store

(Choose Magento 2)
(Project name = vsf-core)

cd vsf-core
yarn install

cd ../

Install vuestorefront/theme-utilities (it installs version @vue-storefront/theme-utilities@0.1.8)

Create theme-utils.config.js file containing:

```module.exports = {
  copy: {
    to: '_theme',
    from: [
      {
        path: 'vsf-core/',
        ignore: [],
        variables: {},
        watch: true
      },
      {
        path: 'theme/',
        ignore: [
        //   '*', // Ignore all files directly in the root of the directory, like package.json, tsconfig.json etc.
        ],
        variables: {},
        watch: true
      }
    ]
  }
};
```
And then run vsf-tu everything compiles just fine, but it fails for one file: vsf-core/modules/magento/plugin.ts

The error log is:

```➜  test-theme vsf-tu

Compiled and copied 510 files to /Users/<user>/Projects/test-theme/_theme.
Failed to compile template '/Users/<user>/Projects/test-theme/vsf-core/modules/magento/plugin.ts'.
ReferenceError: /Users/<user>/Projects/test-theme/vsf-core/modules/magento/plugin.ts:7
    5| import { defaultConfig } from '~/modules/magento/defaultConfig';
    6|
 >> 7| const moduleOptions = JSON.parse('<%= JSON.stringify(options) %>');
    8|
    9| export default integrationPlugin((plugin) => {
    10|   const getCookieName = (property: keyof typeof defaultConfig['cookies']) : string => moduleOptions.cookies?.[property] ?? defaultConfig.cookies[property];

options is not defined
    at eval ("/Users/<user>/Projects/test-theme/vsf-core/modules/magento/plugin.ts":12:41)
    at plugin (/Users/<user>/.config/yarn/global/node_modules/ejs/lib/ejs.js:703:17)
    at /Users/<user>/.config/yarn/global/node_modules/ejs/lib/ejs.js:260:40
    at new Promise (<anonymous>)
    at tryHandleCache (/Users/<user>/.config/yarn/global/node_modules/ejs/lib/ejs.js:258:14)
    at Object.exports.renderFile (/Users/<user>/.config/yarn/global/node_modules/ejs/lib/ejs.js:491:10)
    at parseTemplate (/Users/<user>/.config/yarn/global/node_modules/@vue-storefront/theme-utilities/lib/index.js:144:26)
    at transformTemplate (/Users/<user>/.config/yarn/global/node_modules/@vue-storefront/theme-utilities/lib/index.js:138:47)
    at /Users/<user>/.config/yarn/global/node_modules/@vue-storefront/theme-utilities/lib/index.js:250:42
    at Map.forEach (<anonymous>) {
  path: '/Users/<user>/Projects/test-theme/vsf-core/modules/magento/plugin.ts'
}
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2163:5)
    at transformTemplate (/Users/<user>/.config/yarn/global/node_modules/@vue-storefront/theme-utilities/lib/index.js:138:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Do you maybe know how to fix this?

When I manually copy vsf-core/modules/magento/plugin.ts in the generated _theme directory the application runs just fine.

**Comment by filipsobol** [comment]
Here's the explanation: https://github.com/vuestorefront/theme-utilities/blob/master/README.md?plain=1#L25

Nuxt uses `ejs` (or a similar library) to add module configuration to the file at build-time. This library also uses `ejs`, but because there is no `options` variable (use in `'<%= JSON.stringify(options) %>'`), it throws an error.

We need to add an option to ignore specific files from parsing.

**Comment by filipsobol** [comment]
We added the new option `ignoreParse` that allows specifying files ignored by `ejs`. See updated [README](https://github.com/vuestorefront/theme-utilities#readme) for more details.

Try adding this line to your configuration:

```diff
       {
         path: 'vsf-core/',
         ignore: [],
+        ignoreParse: ['modules/magento/plugin.ts'],
         variables: {},
         watch: true
       },
```
